# Generated by Django 3.2.22 on 2023-11-07 11:02

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('artist', models.CharField(max_length=100)),
                ('created_on', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('medium', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('excerpt', models.TextField(blank=True)),
                ('size', models.CharField(default='', max_length=50)),
                ('year_created', models.PositiveIntegerField(default=2023)),
                ('sold', models.CharField(choices=[('For Sale', 'For Sale'), ('SOLD', 'SOLD')], default='For Sale', max_length=8)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.IntegerField(default=1)),
                ('saved_by', models.ManyToManyField(blank=True, related_name='saved_artworks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContactFormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='brushstrokes.artwork')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
