# Generated by Django 3.2.22 on 2023-11-11 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brushstrokes', '0005_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
