# Generated by Django 3.2.22 on 2023-11-11 22:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brushstrokes', '0006_remove_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='year_created',
            field=models.PositiveIntegerField(default=2023, validators=[django.core.validators.MaxValueValidator(limit_value=2023, message='Year created cannot exceed 2023.')]),
        ),
    ]
